### ISSUE TITLE
在未知场景下会出现Quico Popup窗口无法弹出的问题

### ISSUE THREAD

**Issue by xzjamiezhu** [bowenliang123/Quico#1]
![image](https://cloud.githubusercontent.com/assets/2885270/15806031/a1ffa61a-2b6c-11e6-8f5e-7df12f562a14.png)

如上图：可以看到已经按下Quico图标，但是没有Popup窗口弹出。

**Comment by bowenliang123** [comment]
哈哈，好像确实有这个问题，在连接某VPN的时候居然就打不开了！

**Comment by bowenliang123** [comment]
初步认为是跨域脚本导致的问题。在此commit中尝试解决问题：
https://github.com/bowenliang123/Quico/commit/720c2ea6652fb19955b057dbc831ce297a47208d

请更新插件升级到v1.1.7。若问题重新，在这里继续补充信息。如果问题排除，请关闭issue。

**Comment by bowenliang123** [comment]
嗯…好像并未彻底解决问题。现象是点击后长时间后等待才会弹出popup页。
确定是由GA统计脚本触发了一个gif请求，而被GFW屏蔽后等待超时所导致。
具体GIF请求地址：
https://www.google-analytics.com/__utm.gif?utmwv=5.6.7&utms=16&utmn=1899639760&utmhn=cobbkmppakjllmgndpfmejaflbjfehci&utmcs=UTF-8&utmsr=1366x768&utmvp=232x315&utmsc=24-bit&utmul=zh-cn&utmje=0&utmfl=21.0%20r0&utmdt=Popup&utmhid=1332267900&utmr=-&utmp=%2Fhtml%2Fpopup.html&utmht=1465310610935&utmac=UA-75165383-1&utmcc=__utma%3D64486333.1807510992.1464710368.1465136925.1465310343.4%3B%2B__utmz%3D64486333.1464710368.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)%3B&utmjid=&utmu=qAAAAAAAAAAAAAAAAAAAAAAE~

需要想办法绕开这个问题。

**Comment by bowenliang123** [comment]
我决定删除GoogleAnalysis统计了，在主面板页、弹出页取消了引用，你提到的问题不应该再出现。
v1.2.0已经发布到应用商店，请及时更新。
如果再次重现，请再次提出issue让我跟进吧，感谢！

应用商店的插件应用位置：
https://chrome.google.com/webstore/detail/quico-%E5%BF%AB%E7%A0%81-qr-code-generato/cobbkmppakjllmgndpfmejaflbjfehci?utm_source=chrome-ntp-icon
